#!/usr/bin/env python3
"""
gen_fw_data.py — Convert MNIST hex files into C source for RISC-V firmware.

Reads the hex files produced by mnist_quantize.py (or model_zoo.py) and
generates a C file with const arrays that get linked into the firmware BRAM.

Usage:
  python gen_fw_data.py --data-dir mnist_real_data --image-idx 0 --output model_data.c

The generated file defines:
  const uint32_t fc1_weight_chunks[N1] = { ... };
  const uint32_t fc1_bias[128] = { ... };
  const uint32_t fc2_weight_chunks[N2] = { ... };
  const uint32_t fc2_bias[10] = { ... };
  const uint8_t  test_image[784] = { ... };
  const uint32_t fc1_n_chunks = N1;
  const uint32_t fc2_n_chunks = N2;
  const uint32_t fc1_mult = ..., fc1_shift = ...;
  const uint32_t fc2_mult = ..., fc2_shift = ...;
  const int32_t  hw_zp1 = ..., hw_zp2 = ...;
  const uint32_t expected_label = ...;

WARNING: FC1 weights alone are 25088 × 4 = ~100KB.
This exceeds 32KB BRAM! For real deployment, weights must be:
  a) Stored in external DDR (via PS or DMA)
  b) Or loaded in chunks at runtime
  c) Or use a smaller model

For proof-of-concept, this script generates the full data but prints
a size warning. A small test model (e.g., 784→16→10) would fit in BRAM.
"""

import argparse
import os
import sys
import numpy as np


def read_hex_u32(path):
    with open(path) as f:
        return [int(l.strip(), 16) for l in f if l.strip()]


def read_hex_u8(path):
    with open(path) as f:
        return [int(l.strip(), 16) & 0xFF for l in f if l.strip()]


def write_c_array_u32(f, name, data):
    f.write(f"const uint32_t {name}[{len(data)}] = {{\n")
    for i in range(0, len(data), 8):
        chunk = data[i : i + 8]
        f.write("    " + ", ".join(f"0x{v:08x}" for v in chunk) + ",\n")
    f.write("};\n\n")


def write_c_array_u8(f, name, data):
    f.write(f"const uint8_t {name}[{len(data)}] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        f.write("    " + ", ".join(f"0x{v:02x}" for v in chunk) + ",\n")
    f.write("};\n\n")


def main():
    parser = argparse.ArgumentParser(description="Generate C data file for firmware")
    parser.add_argument("--data-dir", type=str, default="mnist_real_data")
    parser.add_argument(
        "--image-idx",
        type=int,
        default=0,
        help="Which test image to embed (default: 0)",
    )
    parser.add_argument("--output", type=str, default="model_data.c")
    args = parser.parse_args()

    d = args.data_dir
    idx = args.image_idx
    prefix = f"img_{idx:04d}"

    # Read model data
    fc1_wc = read_hex_u32(f"{d}/fc1_weight_tiles.hex")
    fc2_wc = read_hex_u32(f"{d}/fc2_weight_tiles.hex")
    fc1_bias = read_hex_u32(f"{d}/fc1_bias.hex")
    fc2_bias = read_hex_u32(f"{d}/fc2_bias.hex")
    qp = read_hex_u32(f"{d}/quant_params.hex")
    zps = read_hex_u32(f"{d}/zero_points.hex")

    # Read test image
    img_path = f"{d}/test_images/{prefix}.hex"
    if not os.path.exists(img_path):
        print(f"ERROR: {img_path} not found")
        sys.exit(1)
    test_img = read_hex_u8(img_path)
    label = int(open(f"{d}/test_images/{prefix}_label.txt").read().strip())

    # Convert ZP to signed
    hw_zp1 = np.int32(np.uint32(zps[0]))
    hw_zp2 = np.int32(np.uint32(zps[1]))

    # Size check
    total_bytes = (len(fc1_wc) + len(fc2_wc) + len(fc1_bias) + len(fc2_bias)) * 4 + len(
        test_img
    )
    print(f"Data size: {total_bytes} bytes ({total_bytes / 1024:.1f} KB)")
    if total_bytes > 28000:  # leave room for code + stack
        print(f"WARNING: Data ({total_bytes / 1024:.1f}KB) exceeds 32KB BRAM capacity!")
        print(f"  FC1 weights: {len(fc1_wc) * 4} bytes")
        print(f"  FC2 weights: {len(fc2_wc) * 4} bytes")
        print(f"  For BRAM-only deployment, use a smaller model (e.g., 784→16→10)")
        print(f"  Or load weights from DDR at runtime")
        print(f"  Generating anyway for reference...")

    # Write C file
    with open(args.output, "w") as f:
        f.write(f"// Auto-generated by gen_fw_data.py\n")
        f.write(f"// Data dir: {d}, Image: {prefix}, Label: {label}\n")
        f.write(f"// Total data: {total_bytes} bytes\n\n")
        f.write("#include <stdint.h>\n\n")

        write_c_array_u32(f, "fc1_weight_chunks", fc1_wc)
        write_c_array_u32(f, "fc1_bias", fc1_bias)
        write_c_array_u32(f, "fc2_weight_chunks", fc2_wc)
        write_c_array_u32(f, "fc2_bias", fc2_bias)
        write_c_array_u8(f, "test_image", test_img)

        f.write(f"const uint32_t fc1_n_chunks = {len(fc1_wc)};\n")
        f.write(f"const uint32_t fc2_n_chunks = {len(fc2_wc)};\n\n")
        f.write(f"const uint32_t fc1_mult = {qp[0]};\n")
        f.write(f"const uint32_t fc1_shift = {qp[1]};\n")
        f.write(f"const uint32_t fc2_mult = {qp[2]};\n")
        f.write(f"const uint32_t fc2_shift = {qp[3]};\n\n")
        f.write(f"const int32_t hw_zp1 = {int(hw_zp1)};\n")
        f.write(f"const int32_t hw_zp2 = {int(hw_zp2)};\n\n")
        f.write(f"const uint32_t expected_label = {label};\n")

    print(f"Generated {args.output}")
    print(f"  FC1: {len(fc1_wc)} chunks, FC2: {len(fc2_wc)} chunks")
    print(f"  Image: {prefix}, Label: {label}")
    print(f"  Quant: fc1=({qp[0]},{qp[1]}), fc2=({qp[2]},{qp[3]})")
    print(f"  ZP: fc1={hw_zp1}, fc2={hw_zp2}")


if __name__ == "__main__":
    main()
