`timescale 1ns / 1ps
// ============================================================================
// tb_mnist_e2e.sv — End-to-end MNIST 2-layer MLP inference test
// ============================================================================
// Runs:  FC1 (784→128, ReLU, requantize) → FC2 (128→10, no act, requantize)
//
// Test flow:
//   1. Load FC1 weights (392 tiles) + bias (128) + input image (784)
//   2. Configure layer dims, run FC1, wait done
//   3. Read FC1 output (128 INT8), reload as FC2 input
//   4. Load FC2 weights (80 tiles) + bias (10)
//   5. Configure layer dims, run FC2, wait done
//   6. Read FC2 output (10 INT8), compare with golden
//
// Data files (generated by golden_model.py --mnist-e2e):
//   data_e2e/fc1_weight_tiles.hex   — FC1 weights in tile-packed 32-bit chunks
//   data_e2e/fc1_bias.hex           — FC1 bias INT32 (hex)
//   data_e2e/fc2_weight_tiles.hex   — FC2 weights in tile-packed 32-bit chunks
//   data_e2e/fc2_bias.hex           — FC2 bias INT32 (hex)
//   data_e2e/input_image.hex        — input image UINT8 (hex)
//   data_e2e/fc1_output.hex         — expected FC1 INT8 output
//   data_e2e/fc2_output.hex         — expected FC2 INT8 output (final logits)
//   data_e2e/expected_class.hex     — expected argmax class
//   data_e2e/quant_params.hex       — 4 lines: fc1_mult, fc1_shift, fc2_mult, fc2_shift
//
// Compatible with VCS + Verdi.
// ============================================================================

module tb_mnist_e2e;
  import cim_pkg::*;

  // ---------- Clock / Reset ----------
  logic clk, rst_n;
  initial clk = 0;
  always #4 clk = ~clk;  // 125 MHz (8ns period)

  // ---------- DUT signals ----------
  logic start, soft_rst;
  logic busy, done;
  accel_state_t dbg_state;

  logic [15:0] cfg_in_dim, cfg_out_dim, cfg_n_ib, cfg_n_ob;
  logic signed [31:0] cfg_input_zp;
  logic [31:0] cfg_requant_mult, cfg_requant_shift;
  act_mode_t                                          cfg_act_mode;

  // Weight SRAM (whole-row write interface)
  logic        [         clog2_safe(WSRAM_DEPTH)-1:0] w_rd_idx;
  logic signed [                        WEIGHT_W-1:0] w_rd_tile         [TILE_ROWS] [TILE_COLS];
  logic                                               w_wr_en;
  logic        [               $clog2(TILE_ROWS)-1:0] w_wr_row;
  logic        [         clog2_safe(WSRAM_DEPTH)-1:0] w_wr_tile_idx;
  logic        [              TILE_COLS*WEIGHT_W-1:0] w_wr_row_data;

  // Bias SRAM
  logic        [         clog2_safe(BSRAM_DEPTH)-1:0] b_rd_addr;
  logic signed [                          BIAS_W-1:0] b_rd_data;
  logic                                               b_wr_en;
  logic        [         clog2_safe(BSRAM_DEPTH)-1:0] b_wr_addr;
  logic        [                                31:0] b_wr_data;

  // Input buffer (whole-tile write interface)
  logic        [clog2_safe(MAX_IN_DIM/TILE_COLS)-1:0] ibuf_rd_idx;
  logic        [                         X_EFF_W-1:0] ibuf_x_eff        [TILE_COLS];
  logic                                               ibuf_wr_en;
  logic        [clog2_safe(MAX_IN_DIM/TILE_COLS)-1:0] ibuf_wr_tile_idx;
  logic        [               TILE_COLS*INPUT_W-1:0] ibuf_wr_tile_data;
  logic        [                         INPUT_W-1:0] ibuf_x_tile       [TILE_COLS];

  // Output buffer
  logic                                               obuf_wr_en;
  logic        [         clog2_safe(MAX_OUT_DIM)-1:0] obuf_wr_addr;
  logic signed [                        OUTPUT_W-1:0] obuf_wr_data;
  logic        [         clog2_safe(MAX_OUT_DIM)-1:0] obuf_rd_addr;
  logic signed [                        OUTPUT_W-1:0] obuf_rd_data;
  logic        [         clog2_safe(MAX_OUT_DIM)-1:0] pred_class;

  logic [63:0] perf_cycles, perf_macs;

  // ---------- Layer config constants ----------
  localparam int FC1_IN = 784;
  localparam int FC1_OUT = 128;
  localparam int FC1_NIB = (FC1_IN + TILE_COLS - 1) / TILE_COLS;  // 49
  localparam int FC1_NOB = (FC1_OUT + TILE_ROWS - 1) / TILE_ROWS;  // 8
  localparam int FC1_ZP = -128;

  localparam int FC2_IN = 128;
  localparam int FC2_OUT = 10;
  localparam int FC2_NIB = (FC2_IN + TILE_COLS - 1) / TILE_COLS;  // 8
  localparam int FC2_NOB = (FC2_OUT + TILE_ROWS - 1) / TILE_ROWS;  // 1
  localparam int FC2_ZP = 0;

  localparam int FC1_N_TILES = FC1_NOB * FC1_NIB;  // 392
  localparam int FC2_N_TILES = FC2_NOB * FC2_NIB;  // 8

  localparam int CHUNKS_PER_TILE = TILE_ROWS * TILE_COLS / (32 / WEIGHT_W);  // 64

  // ---------- Golden data storage ----------
  // Weight tiles: stored as flat 32-bit chunks, [n_tiles * chunks_per_tile]
  logic [31:0] fc1_w_chunks[FC1_N_TILES * CHUNKS_PER_TILE];
  logic [31:0] fc2_w_chunks[FC2_N_TILES * CHUNKS_PER_TILE];
  logic [31:0] fc1_bias_hex[FC1_OUT];
  logic [31:0] fc2_bias_hex[FC2_OUT];
  logic [7:0] input_image[FC1_IN];
  logic signed [7:0] fc1_expected[FC1_OUT];
  logic signed [7:0] fc2_expected[FC2_OUT];
  logic [31:0] expected_class[1];  // array for $readmemh
  // Quant params: fc1_mult, fc1_shift, fc2_mult, fc2_shift
  logic [31:0] quant_params[4];

  int err_cnt;

  // ---------- Memory instantiation ----------
  weight_sram #(
      .DEPTH(WSRAM_DEPTH)
  ) u_wsram (
      .clk        (clk),
      .wr_en      (w_wr_en),
      .wr_row     (w_wr_row),
      .wr_tile_idx(w_wr_tile_idx),
      .wr_row_data(w_wr_row_data),
      .rd_tile_idx(w_rd_idx),
      .rd_tile    (w_rd_tile)
  );

  bias_sram #(
      .DEPTH(BSRAM_DEPTH)
  ) u_bsram (
      .clk    (clk),
      .wr_en  (b_wr_en),
      .wr_addr(b_wr_addr),
      .wr_data(b_wr_data),
      .rd_addr(b_rd_addr),
      .rd_data(b_rd_data)
  );

  input_buffer #(
      .MAX_LEN(MAX_IN_DIM)
  ) u_ibuf (
      .clk         (clk),
      .wr_en       (ibuf_wr_en),
      .wr_tile_idx (ibuf_wr_tile_idx),
      .wr_tile_data(ibuf_wr_tile_data),
      .rd_tile_idx (ibuf_rd_idx),
      .input_zp    (cfg_input_zp),
      .x_tile      (ibuf_x_tile),
      .x_eff       (ibuf_x_eff)
  );

  output_buffer #(
      .MAX_LEN(MAX_OUT_DIM)
  ) u_obuf (
      .clk       (clk),
      .rst_n     (rst_n),
      .wr_en     (obuf_wr_en),
      .wr_addr   (obuf_wr_addr),
      .wr_data   (obuf_wr_data),
      .rd_addr   (obuf_rd_addr),
      .rd_data   (obuf_rd_data),
      .out_dim   (cfg_out_dim[clog2_safe(MAX_OUT_DIM)-1:0]),
      .pred_class(pred_class)
  );

  // ---------- DUT ----------
  cim_accel_core dut (
      .clk              (clk),
      .rst_n            (rst_n),
      .start            (start),
      .soft_rst         (soft_rst),
      .busy             (busy),
      .done             (done),
      .dbg_state        (dbg_state),
      .cfg_in_dim       (cfg_in_dim),
      .cfg_out_dim      (cfg_out_dim),
      .cfg_n_ib         (cfg_n_ib),
      .cfg_n_ob         (cfg_n_ob),
      .cfg_input_zp     (cfg_input_zp),
      .cfg_requant_mult (cfg_requant_mult),
      .cfg_requant_shift(cfg_requant_shift),
      .cfg_act_mode     (cfg_act_mode),
      .w_rd_tile_idx    (w_rd_idx),
      .w_rd_tile        (w_rd_tile),
      .b_rd_addr        (b_rd_addr),
      .b_rd_data        (b_rd_data),
      .ibuf_rd_tile_idx (ibuf_rd_idx),
      .ibuf_x_eff       (ibuf_x_eff),
      .obuf_wr_en       (obuf_wr_en),
      .obuf_wr_addr     (obuf_wr_addr),
      .obuf_wr_data     (obuf_wr_data),
      .perf_cycles      (perf_cycles),
      .perf_macs        (perf_macs)
  );

  // ==========================================================================
  // Helper tasks — adapted for whole-word BRAM interface
  // ==========================================================================

  task automatic write_weight_row(input int tile_idx, input int row_idx,
                                  input logic [TILE_COLS*WEIGHT_W-1:0] row_data);
    @(posedge clk);
    w_wr_en       <= 1'b1;
    w_wr_tile_idx <= tile_idx;
    w_wr_row      <= row_idx;
    w_wr_row_data <= row_data;
    @(posedge clk);
    w_wr_en <= 1'b0;
  endtask

  task automatic write_bias(input int addr, input logic [31:0] data);
    @(posedge clk);
    b_wr_en   <= 1'b1;
    b_wr_addr <= addr;
    b_wr_data <= data;
    @(posedge clk);
    b_wr_en <= 1'b0;
  endtask

  task automatic write_input_tile(input int tile_idx,
                                  input logic [TILE_COLS*INPUT_W-1:0] tile_data);
    @(posedge clk);
    ibuf_wr_en        <= 1'b1;
    ibuf_wr_tile_idx  <= tile_idx;
    ibuf_wr_tile_data <= tile_data;
    @(posedge clk);
    ibuf_wr_en <= 1'b0;
  endtask

  task automatic trigger_and_wait();
    @(posedge clk);
    start <= 1'b1;
    @(posedge clk);
    start <= 1'b0;
    wait (done);
    repeat (3) @(posedge clk);
  endtask

  task automatic read_obuf(input int addr, output logic signed [7:0] val);
    obuf_rd_addr = addr;
    repeat (2) @(posedge clk);  // 1-cycle BRAM read latency
    val = obuf_rd_data;
  endtask

  // ==========================================================================
  // Load weight tiles from flat chunk array — assemble rows, write whole-word
  // ==========================================================================
  localparam int CHUNKS_PER_ROW_TB = TILE_COLS / (32 / WEIGHT_W);  // 4
  localparam int ROW_W_TB = TILE_COLS * WEIGHT_W;  // 128

  task automatic load_weight_tiles(input int n_tiles, input logic [31:0] chunk_array[],
                                   input int chunks_per_tile_val);
    for (int t = 0; t < n_tiles; t++) begin
      for (int row = 0; row < TILE_ROWS; row++) begin
        automatic logic [ROW_W_TB-1:0] row_data = '0;
        for (int cg = 0; cg < CHUNKS_PER_ROW_TB; cg++) begin
          automatic int ci = row * CHUNKS_PER_ROW_TB + cg;
          row_data[cg*32+:32] = chunk_array[t*chunks_per_tile_val+ci];
        end
        write_weight_row(t, row, row_data);
      end
    end
  endtask

  // ==========================================================================
  // Main test sequence
  // ==========================================================================
  initial begin
    $display("============================================================");
    $display("TB: MNIST End-to-End (784→128→10), PAR_OB=%0d", PAR_OB);
    $display("============================================================");

`ifdef VCS
    $fsdbDumpfile("tb_mnist_e2e.fsdb");
    $fsdbDumpvars(0, tb_mnist_e2e, "+all");
`endif

    // ---- Init ----
    err_cnt      = 0;
    rst_n        = 0;
    start        = 0;
    soft_rst     = 0;
    w_wr_en      = 0;
    b_wr_en      = 0;
    ibuf_wr_en   = 0;
    obuf_rd_addr = '0;

    // ---- Load golden data from hex files ----
    $readmemh("data_e2e/fc1_weight_tiles.hex", fc1_w_chunks);
    $readmemh("data_e2e/fc2_weight_tiles.hex", fc2_w_chunks);
    $readmemh("data_e2e/fc1_bias.hex", fc1_bias_hex);
    $readmemh("data_e2e/fc2_bias.hex", fc2_bias_hex);
    $readmemh("data_e2e/input_image.hex", input_image);
    $readmemh("data_e2e/fc1_output.hex", fc1_expected);
    $readmemh("data_e2e/fc2_output.hex", fc2_expected);
    $readmemh("data_e2e/expected_class.hex", expected_class);
    $readmemh("data_e2e/quant_params.hex", quant_params);

    $display("Golden data loaded.");
    $display("  FC1: %0d tiles × %0d chunks", FC1_N_TILES, CHUNKS_PER_TILE);
    $display("  FC2: %0d tiles × %0d chunks", FC2_N_TILES, CHUNKS_PER_TILE);
    $display("  Quant: fc1_mult=%0d fc1_shift=%0d fc2_mult=%0d fc2_shift=%0d", quant_params[0],
             quant_params[1], quant_params[2], quant_params[3]);

    // ---- Reset ----
    repeat (20) @(posedge clk);
    rst_n = 1;
    repeat (5) @(posedge clk);

    // ================================================================
    // Layer 1: FC1 784→128 (ReLU)
    // ================================================================
    $display("\n=== LAYER 1: FC1 784→128 ReLU ===");

    // Configure
    cfg_in_dim        = FC1_IN;
    cfg_out_dim       = FC1_OUT;
    cfg_n_ib          = FC1_NIB;
    cfg_n_ob          = FC1_NOB;
    cfg_input_zp      = FC1_ZP;
    cfg_requant_mult  = quant_params[0];
    cfg_requant_shift = quant_params[1];
    cfg_act_mode      = ACT_RELU;

    // Load FC1 weights
    $display("  Loading FC1 weights (%0d tiles)...", FC1_N_TILES);
    load_weight_tiles(FC1_N_TILES, fc1_w_chunks, CHUNKS_PER_TILE);

    // Load FC1 bias
    $display("  Loading FC1 bias (%0d values)...", FC1_OUT);
    for (int i = 0; i < FC1_OUT; i++) write_bias(i, fc1_bias_hex[i]);

    // Load input image as tiles (16 bytes per tile)
    $display("  Loading input image (%0d pixels)...", FC1_IN);
    for (int tile = 0; tile < FC1_NIB; tile++) begin
      automatic logic [TILE_COLS*INPUT_W-1:0] tdata = '0;
      for (int c = 0; c < TILE_COLS; c++) begin
        automatic int idx = tile * TILE_COLS + c;
        if (idx < FC1_IN) tdata[c*INPUT_W+:INPUT_W] = input_image[idx];
      end
      write_input_tile(tile, tdata);
    end

    repeat (5) @(posedge clk);

    // Run FC1
    $display("  Running FC1...");
    trigger_and_wait();
    $display("  FC1 done! cycles=%0d MACs=%0d", perf_cycles, perf_macs);

    // Read FC1 output and compare
    $display("  Comparing FC1 output...");
    begin
      logic signed [7:0] fc1_rtl_out[FC1_OUT];
      int fc1_err = 0;
      for (int i = 0; i < FC1_OUT; i++) begin
        read_obuf(i, fc1_rtl_out[i]);
        if (fc1_rtl_out[i] !== fc1_expected[i]) begin
          $display("  FC1 MISMATCH [%0d]: RTL=%0d Golden=%0d", i, fc1_rtl_out[i], fc1_expected[i]);
          fc1_err++;
        end
      end
      if (fc1_err == 0) $display("  FC1: ALL %0d outputs MATCH", FC1_OUT);
      else begin
        $display("  FC1: %0d / %0d MISMATCHES", fc1_err, FC1_OUT);
        err_cnt += fc1_err;
      end

      // ================================================================
      // Layer 2: FC2 128→10 (no activation)
      // ================================================================
      $display("\n=== LAYER 2: FC2 128→10 (no activation) ===");

      // Reconfigure for FC2
      cfg_in_dim        = FC2_IN;
      cfg_out_dim       = FC2_OUT;
      cfg_n_ib          = FC2_NIB;
      cfg_n_ob          = FC2_NOB;
      cfg_input_zp      = FC2_ZP;
      cfg_requant_mult  = quant_params[2];
      cfg_requant_shift = quant_params[3];
      cfg_act_mode      = ACT_NONE;

      // Load FC2 weights
      $display("  Loading FC2 weights (%0d tiles)...", FC2_N_TILES);
      load_weight_tiles(FC2_N_TILES, fc2_w_chunks, CHUNKS_PER_TILE);

      // Load FC2 bias
      $display("  Loading FC2 bias (%0d values)...", FC2_OUT);
      for (int i = 0; i < FC2_OUT; i++) write_bias(i, fc2_bias_hex[i]);

      // Load FC1 output as FC2 input (re-interpret signed INT8 as UINT8)
      $display("  Loading FC1 output as FC2 input...");
      for (int tile = 0; tile < FC2_NIB; tile++) begin
        automatic logic [TILE_COLS*INPUT_W-1:0] tdata = '0;
        for (int c = 0; c < TILE_COLS; c++) begin
          automatic int idx = tile * TILE_COLS + c;
          if (idx < FC2_IN) tdata[c*INPUT_W+:INPUT_W] = fc1_rtl_out[idx];
        end
        write_input_tile(tile, tdata);
      end

      repeat (5) @(posedge clk);

      // Run FC2
      $display("  Running FC2...");
      trigger_and_wait();
      $display("  FC2 done! cycles=%0d MACs=%0d", perf_cycles, perf_macs);
    end

    // Read FC2 output and compare
    $display("  Comparing FC2 output (final logits)...");
    begin
      int fc2_err = 0;
      logic signed [7:0] val;
      for (int i = 0; i < FC2_OUT; i++) begin
        read_obuf(i, val);
        if (val !== fc2_expected[i]) begin
          $display("  FC2 MISMATCH [%0d]: RTL=%0d Golden=%0d", i, val, fc2_expected[i]);
          fc2_err++;
        end else begin
          $display("  logit[%0d] = %4d  OK", i, val);
        end
      end
      if (fc2_err == 0) $display("  FC2: ALL %0d outputs MATCH", FC2_OUT);
      else begin
        $display("  FC2: %0d / %0d MISMATCHES", fc2_err, FC2_OUT);
        err_cnt += fc2_err;
      end
    end

    // Check predicted class
    $display("\n  Predicted class (argmax) = %0d, expected = %0d", pred_class, expected_class[0]);
    if (pred_class != expected_class[0][clog2_safe(MAX_OUT_DIM)-1:0]) begin
      $display("  PRED CLASS MISMATCH!");
      err_cnt++;
    end

    // ================================================================
    // Summary
    // ================================================================
    $display("\n============================================================");
    $display("MNIST E2E Test Summary:");
    $display("  Total errors: %0d", err_cnt);
    if (err_cnt == 0) $display("  >>> ALL TESTS PASSED <<<");
    else $display("  >>> SOME TESTS FAILED <<<");
    $display("============================================================");

    #200;
    $finish;
  end

  // ---- Timeout ----
  initial begin
    #100_000_000;
    $display("ERROR: Timeout! State=%0d", dbg_state);
    $finish;
  end

endmodule
