## ============================================================================
## cim_soc.xdc — Constraints for CIM SoC on PYNQ-Z2 (xc7z020clg400-1)
## ============================================================================
## Top-level module: system_wrapper (auto-generated by Vivado make_wrapper)
##
## Architecture:
##   Zynq PS7 (ARM Cortex-A9) ← AXI-Lite → CIM Accelerator IP (PL)
##   All data goes through PS: Python on PYNQ loads weights/inputs via MMIO,
##   triggers inference, reads back results. No standalone PL I/O needed.
##
## External ports of system_wrapper:
##   - DDR      (14-bit addr, 3-bit ba, 32-bit dq, 4-bit dm/dqs, ctrl)
##   - FIXED_IO (54-bit MIO, ps_clk, ps_porb, ps_srstb, ddr_vrn, ddr_vrp)
##
## These are ALL dedicated PS-side pins on the Zynq — their physical pin
## assignments are FIXED in silicon and handled automatically by Vivado's
## board automation (apply_bd_automation with PYNQ-Z2 board file).
## You do NOT and MUST NOT manually constrain DDR/FIXED_IO pin locations.
## ============================================================================

## ============================================================================
## 1. TIMING CONSTRAINTS
## ============================================================================
## The Zynq PS generates FCLK_CLK0 internally and feeds it to the PL fabric.
## vivado_build.tcl sets PCW_FPGA0_PERIPHERAL_FREQMHZ = 60.
## Vivado auto-creates a clock object for FCLK_CLK0 during synthesis, but
## we explicitly define it here to ensure timing analysis is correct and to
## give it a readable name.
##
## The PS7 IP block already propagates this clock, so create_clock on the
## buffer output pin is the standard approach for Zynq designs.
## ============================================================================

## FCLK_CLK0 = 100 MHz → period = 10.000 ns (C1: 60→100MHz with TILE_SPLIT_FACTOR=4)
## The exact get_pins path depends on the BD hierarchy; Vivado typically names
## the output buffer as shown below. If synthesis warns about the pin not being
## found, the auto-generated clock from PS7 IP will still be used.
create_clock -name fclk0 -period 10.000 \
    [get_pins -quiet system_i/ps7/inst/PS7_i/FCLKCLK[0]]

## C1: Limit fanout on x_eff_reg to prevent synthesis from creating replicas
## placed far from the DSP column. The critical path at 100MHz is:
##   x_eff_reg_replica → DSP48E1 → 4×CARRY4 → psum_reg (10.615ns, WNS=-0.800)
set_property MAX_FANOUT 16 [get_cells -hier -filter {NAME =~ *x_eff_reg_reg*}]

## ============================================================================
## 2. FALSE PATHS / ASYNC CROSSINGS
## ============================================================================
## In this design, everything runs on FCLK_CLK0 (single clock domain), so
## there are no CDC paths to constrain. If you later add a second clock
## (e.g., for HDMI, audio, or external ADC), add set_clock_groups or
## set_false_path between the domains here.

## ============================================================================
## 3. DDR & FIXED_IO — NO MANUAL PIN CONSTRAINTS NEEDED
## ============================================================================
## On Zynq-7000, the DDR and MIO pins are hardwired to the PS block in
## silicon. When you use apply_bd_automation with the PYNQ-Z2 board file,
## Vivado automatically configures all DDR timing, termination, and pin
## assignments inside the PS7 IP. Manual LOC/IOSTANDARD constraints for
## DDR_addr, DDR_dq, FIXED_IO_mio, etc. are INCORRECT for Zynq designs
## and will cause DRC errors.
##
## Your previous project's PYNQ-Z2_v1_0.xdc had manual DDR pin assignments
## — those were wrong (the pin names like A7, B7 don't match the actual
## PYNQ-Z2 package). The board file handles everything correctly.

## ============================================================================
## 4. OPTIONAL: PL-SIDE I/O (uncomment if you add debug signals)
## ============================================================================
## This design has NO PL-side I/O — all communication is via AXI through
## the PS. If you later want to add debug LEDs, UART, or buttons, uncomment
## and modify the relevant lines below.
##
## Reference pin map for PYNQ-Z2 (xc7z020clg400-1):
##
## ---- LEDs ----
## LED0  R14    LED1  P14    LED2  N16    LED3  M14
##
## ---- RGB LEDs ----
## LED4_B  L15   LED4_G  G17   LED4_R  N15
## LED5_B  G14   LED5_G  L14   LED5_R  M15
##
## ---- Buttons (directly active-high, active when pressed) ----
## BTN0  D19    BTN1  D20    BTN2  L20    BTN3  L19
##
## ---- Switches ----
## SW0   M20    SW1   M19
##
## ---- PMOD A (accent: accent accent accent pin) ----
## JA[0]  Y18   JA[1]  Y19   JA[2]  AA7   JA[3]  Y16
## JA[4]  AB7   JA[5]  AA6   JA[6]  Y6    JA[7]  T6
##
## ---- PMOD B ----
## JB[0]  T20   JB[1]  U20   JB[2]  V20   JB[3]  W20
## JB[4]  Y18   JB[5]  Y19   JB[6]  W18   JB[7]  W19

## Example: connect irq_done to an LED for visual feedback
## (requires making irq_done external in the block design first)
#
# set_property PACKAGE_PIN R14 [get_ports {irq_done_0}]
# set_property IOSTANDARD LVCMOS33 [get_ports {irq_done_0}]

## ============================================================================
## 5. BITSTREAM CONFIGURATION
## ============================================================================
## PYNQ boots from SD card; the PS configures the PL. These settings ensure
## reliable bitstream loading.

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLDOWN [current_design]

## ============================================================================
## 6. IMPLEMENTATION STRATEGY HINTS
## ============================================================================
## The CIM accelerator uses wide BRAM arrays and many DSP48 multipliers.
## Allow Vivado extra freedom in placement.

#set_property STEPS.PLACE_DESIGN.ARGS.DIRECTIVE ExtraNetDelay_high [get_runs impl_1]
#set_property STEPS.ROUTE_DESIGN.ARGS.DIRECTIVE AggressiveExplore [get_runs impl_1]
